### ISSUE TITLE
Remove plg_authentication_ldap

### ISSUE THREAD

**Issue by johanjanssens** [joomladevelopers/joomla-spark#24]
See: https://github.com/joomlatools/joomlatools-platform/issues/60

_Rationale_: Not a core feature.

**Comment by joomlacorner** [comment]
@johanjanssens  This's issue is duplicate with #26 ?

coz, Now, I don't see  https://github.com/joomladevelopers/joomla-spark/tree/master/plugins/authentication/ldap folder in master branch.

**Comment by johanjanssens** [comment]
@joomlacorner You are right. This is a duplicate indeed. Closing.
