### ISSUE TITLE
Installation halts at step 3

### ISSUE THREAD

**Issue by koobitor** [joomladevelopers/joomla-spark#72]
- loop install on step 3
- it don't create configuration.php

![screen shot 2559-08-03 at 4 04 35 pm](https://cloud.githubusercontent.com/assets/747341/17360102/0403eede-5994-11e6-86bb-b660ddcf4120.png)

**Comment by johanjanssens** [comment]
Can you try to debug and see if you can find the issue?

**Comment by johanjanssens** [comment]
@koobitor The problem is that mod_stats_admin was not completely removed from the sql in #15 Fixing this.
