### ISSUE TITLE
Upgrade to Joomla 3.6.1

### ISSUE THREAD

**Issue by johanjanssens** [joomladevelopers/joomla-spark#79]
References:

- https://github.com/joomla/joomla-cms/compare/3.6.0...3.6.1 
- https://github.com/joomla/joomla-cms/commits/3.6.1

**Comment by joomlacorner** [comment]
question, why we don't skip 3.6.1 to 3.6.2 with patch from3.6.0 to 3.6.2 ? (Joomla_3.6.x_to_3.6.2-Stable-Patch_Package)

Coz, 3.6.1 it's come with bug.

**Comment by johanjanssens** [comment]
@joomlacorner True. We can just upgrade to 3.6.2 in one go indeed, no need to patch twice. Will close this ticket and adjust the other one.
